# Generated by Django 2.0 on 2020-06-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_user_type',
            new_name='user_type',
        ),
    ]
